server:
  port: 8081

###eureka服务注册地址
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9001/eureka/
spring:
  application:
    name: zuul-server

## 配置网关反向代理
zuul:
  routes:
    ###服务接口
    api-user:
      path: /user/**
      serviceId: user-server
    api-pay:
      path: /pay/**
      serviceId: pay-server
    api-bbs:
      path: /bbs/**
      serviceId: bbs-server
