server:
  port: 80

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9001/eureka/

spring:
  application:
    name: web-cms
  #redis连接信息
  redis:
    host: 192.168.93.129
    password: 123456
    port: 6379
    jedis:
      pool:
        max-idle: 100
        min-idle: 1
        max-active: 1000
        max-wait: -1
  ### resources
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
  ### freemarker
  freemarker:
    cache: false
    request-context-attribute: request
    template-loader-path: classpath:/templates/
    suffix: .ftl
    charset: UTF-8
    settings:
      number_format: 0

### xxl-sso
xxl:
  sso:
    logout:
      path: /logout
    server: http://xxlssoserver.com:8080/xxl-sso-server
xxl-sso:
  excluded:
    paths: ''






