## 开发环境配置
server:
    port: 8080

## spring相关配置
spring:
    ## 数据源配置
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/opendev?useUnicode=true&characterEncoding=utf8
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
    ## redis配置
    redis:
        host: 127.0.0.1
        port: 6379
        password : 123456
        timeout: 1800
        jedis:
            pool:
                max-active: 8
                max-idle: 8
                min-idle: 0


## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
    mapper-locations: com.opendev.mapper.xml.*.xml  #注意：一定要对应mapper映射xml文件的所在路径
    type-aliases-package: com.opendev.model  # 注意：对应实体类的路径

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

##日志配置
logging:
    level:
      com.opendev: DEBUG

