###服务端口号
server:
  port: 9001

spring:
  cloud:
    inetutils:
      # 忽略指定网卡，支持正则表达式（这里使用正则表达式忽略所有虚拟机网卡）
      ignored-interfaces: ['VMware.*']

###eureka 基本信息配置
eureka:
  instance:
    ###注册到eurekaip地址
    hostname: 192.168.2.146
    #注册时使用ip而不是主机名
    prefer-ip-address: true
  client:
    ###表示是否注册自身到eureka服务器， 做集群是设置成true 生产配置为true
    register-with-eureka: false
    ###表示是否从eureka服务器获得注册信息，生产配置为true
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    ###关闭自我保护模式（缺省为打开）
    enable-self-preservation: false
    ###续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms），测试环境修改小点
    eviction-interval-timer-in-ms: 5000