server:
  port: 8004

eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://192.168.2.98:9001/eureka/

spring:
  application:
    name: wechat-server


