server:
  port: 8002

##eureka注册中心相关配置
eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}
    ###发呆时间，即服务续约到期时间（缺省为90秒，生产使用缺省时间，测试环境修改小点）
    ##lease-expiration-duration-in-seconds: 10
    ###心跳时间，生产使用缺省时间，即服务续约间隔时间（缺省为30秒，生产使用缺省时间，测试环境修改小点）
    ##lease-renewal-interval-in-seconds: 10
  client:
    ###默认为30s 生产使用缺省时间，测试环境修改小点
    ##registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://192.168.2.98:9001/eureka/

##Spring相关配置
spring:
  application:
    name: pay-server
  #数据库连接信息
  datasource:
    name: test
    url: jdbc:mysql://192.168.93.128:3306/opendevclub-pay?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  #redis连接信息
  redis:
    host: 127.0.0.1
    password: 123456
    port: 6379
    jedis:
      pool:
        max-idle: 100
        min-idle: 1
        max-active: 1000
        max-wait: -1
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.opendev.bean
  mapper-locations: classpath:mapper/*Mapper.xml

# 默认之配置为TM的本机默认端口
tx-lcn:
  client:
    manager-address: 127.0.0.1:8070

## Swagger相关配置
swagger:
  base-package: com.opendev.service
  title: SpringCloud2.x构建微服务电商项目--支付服务接口
  description: 基于SpringBoot+Shiro+MyBatis+Redis+Layui+Swagger的前后端分离开源项目
  version: 1.0
  terms-of-service-url: www.opdev.club
  contact:
    name: 郭洪奎
    email: hungkuei@163.com




