### web
server:
  port: 8080
  servlet:
    context-path: /xxl-sso-server

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9001/eureka/

spring:
### freemarker
  freemarker:
    charset: UTF-8
    request-context-attribute: request
    settings:
      number_format: 0.##########
    suffix: .ftl
    templateLoaderPath: classpath:/templates/
### resources
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
  application:
    name: xxl-sso-server
  cloud:
    inetutils:
      # 忽略指定网卡，支持正则表达式（这里使用正则表达式忽略所有虚拟机网卡）
      ignored-interfaces: ['VMware.*']
### xxl-sso
xxl:
  sso:
    redis:
      address: redis://192.168.93.129:6379
      password: 123456
      expire:
        minite: 1440