##开发环境下服务端口
server:
  port: 8002

spring:
  datasource: ## 阿里druid数据源配置
    url: jdbc:mysql://localhost:3306/opendev?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  redis:  ## redis基本配置
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 1800
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

##mybatis配置
mybatis:
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  type-aliases-package: com.opendev.model
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false


##pagehelper分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

##控制台日志打印
logging:
  level:
    com.opendev: DEBUG








